### ISSUE TITLE
User subscriptions interface

### ISSUE THREAD

**Issue by DeeZone** [DoSomething/mbc-user-subscriptions#2]
Add web (http) accessible web page that presents a user email subscription preferences form to allow the user to selectively change their email subscription preferences.

### Technical notes
- [x] page accessed by a "Unsubscribe" link at the bottom of DoSomething email message. 
```
http://subscriptions.dosomething.org?targetEmail=<target email>&key=21jhg321344554hjgjhg1232
```
`key` is a md5 hash of:
  - [x] email 
  - [x] Drupal UID
  - [x] current date
```
test@test.com, 12345, 2015/01/30
```
The date ensures that the link is time sensitive (expires after a time period). Logic will need to test key values of the current date and each previous day for the last 6 days (one week).

**Related**: https://github.com/DoSomething/mb-toolbox/issues/24

#### Test if the link is valid by:
- [x] looking up the Drupal UID for the target email
- [x] the current date (or the date within the acceptable expiry date range) combined to create a md5 hash value to compare with the supplied `key` value in the link accessing the page.
**Related**: https://github.com/DoSomething/mbc-user-subscriptions/issues/6

#### Page flow
- [x] If the md5 hash test passes, present the user with a simple form with their current subscription settings as checkboxes. 
- [x] If it fails, inform the user of the expired link and instruct the user to log into the Drupal site to adjust their profile. **Related**: https://github.com/DoSomething/mbc-user-subscriptions/issues/4
- [x] A form submission will send the updated preferences to `mb-users` via `mb-users-api`. **Related**: https://github.com/DoSomething/mbc-user-subscriptions/issues/1
  - [x] Send user to "Thank You" page to confirm their updated preferences have been made.

#### UI
- [x] Responsive review to ensure unsubscribe functionality works on all platforms: https://github.com/DoSomething/mbc-user-subscriptions/issues/7

**Related**:
https://github.com/DoSomething/dosomething/issues/3522

**Comment by DeeZone** [comment]
@barryclark I'll need some fender responsive work done on the unsubscribe web page to ensure users can change / unsubscribe. Is it best to make the issue here and assign @DFurnes  / @weerd ?

**Comment by barryclark** [comment]
@DeeZone If you make the issue here and assign me for now that'd be great. Thanks!

**Comment by DeeZone** [comment]
@barryclark As requested: https://github.com/DoSomething/mbc-user-subscriptions/issues/7
